[package]
name = "ethereum-proxy"
version = "0.1.0"
authors = ["Tomasz DrwiÄ™ga <tomusdrw@gmail.com>"]

[dependencies]
clap = { version = "2.32", features = ["yaml"] }
simple-cache = { path = "../plugins/simple-cache" }
upstream = { path = "../plugins/upstream" }
rpc-proxy = { path = "../generic-proxy" }
